insert into FOOTBALL_TEAM (nombre, liga, pais) values ('Real Madrid', 'La Liga', 'España');
insert into FOOTBALL_TEAM (nombre, liga, pais) values ('FC Barcelona', 'La Liga', 'España');
insert into FOOTBALL_TEAM (nombre, liga, pais) values ('Manchester United', 'Premier League', 'Inglaterra');
insert into FOOTBALL_TEAM (nombre, liga, pais) values ('Liverpool FC', 'Premier League', 'Inglaterra');
insert into FOOTBALL_TEAM (nombre, liga, pais) values ('Juventus FC', 'Serie A', 'Italia');
insert into FOOTBALL_TEAM (nombre, liga, pais) values ('AC Milan', 'Serie A', 'Italia');
insert into FOOTBALL_TEAM (nombre, liga, pais) values ('Bayern Munich', 'Bundesliga', 'Alemania');
insert into FOOTBALL_TEAM (nombre, liga, pais) values ('Borussia Dortmund', 'Bundesliga', 'Alemania');
insert into FOOTBALL_TEAM (nombre, liga, pais) values ('Paris Saint-Germain', 'Ligue 1', 'Francia');
insert into FOOTBALL_TEAM (nombre, liga, pais) values ('Olympique de Marseille', 'Ligue 1', 'Francia');
insert into FOOTBALL_TEAM (nombre, liga, pais) values ('FC Porto', 'Primeira Liga', 'Portugal');
insert into FOOTBALL_TEAM (nombre, liga, pais) values ('Sporting CP', 'Primeira Liga', 'Portugal');
insert into FOOTBALL_TEAM (nombre, liga, pais) values ('Ajax Amsterdam', 'Eredivisie', 'Países Bajos');
insert into FOOTBALL_TEAM (nombre, liga, pais) values ('Feyenoord', 'Eredivisie', 'Países Bajos');
insert into FOOTBALL_TEAM (nombre, liga, pais) values ('Celtic FC', 'Scottish Premiership', 'Escocia');
insert into FOOTBALL_TEAM (nombre, liga, pais) values ('Rangers FC', 'Scottish Premiership', 'Escocia');
insert into FOOTBALL_TEAM (nombre, liga, pais) values ('Galatasaray SK', 'Süper Lig', 'Turquía');
insert into FOOTBALL_TEAM (nombre, liga, pais) values ('Fenerbahçe SK', 'Süper Lig', 'Turquía');
insert into FOOTBALL_TEAM (nombre, liga, pais) values ('FC Zenit Saint Petersburg', 'Premier League Rusa', 'Rusia');
insert into FOOTBALL_TEAM (nombre, liga, pais) values ('Spartak Moscow', 'Premier League Rusa', 'Rusia');
insert into FOOTBALL_TEAM (nombre, liga, pais) values ('SL Benfica', 'Primeira Liga', 'Portugal');
insert into FOOTBALL_TEAM (nombre, liga, pais) values ('Besiktas JK', 'Süper Lig', 'Turquía');
insert into FOOTBALL_TEAM (nombre, liga, pais) values ('SSC Napoli', 'Serie A', 'Italia');
insert into FOOTBALL_TEAM (nombre, liga, pais) values ('Atlético Madrid', 'La Liga', 'España');
